---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.9

suites:
  - name: default
    run_list:
      - recipe[server::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
